### ISSUE TITLE
Re maintaining dirs crate

### ISSUE THREAD

**Issue by lzutao** [xdg-rs/dirs#4]
@tbu-, You have owner permission on crates.io, don't you?

I mailed Simon (soc) asking for publishing permission but he
hasn't answered yet.

What are we going to do next to inform community about
maintaining dirs development?

**Comment by lzutao** [comment]
Nothing to do here!

**Comment by pickfire** [comment]
Why not just re-publish it as `dirs`? Using something like `dirs_next` is not discoverable at first.

**Comment by lzutao** [comment]
The main owner of dirs crate is [Simon](https://github.com/soc). He doesn't want pass ownership to us. So if we use Tobias permission to publish, Simon may yank that version.or act unreliably.

**Comment by pickfire** [comment]
How about using the crate `xdg` since this is named `xdg-rs`? https://crates.io/crates/xdg

**Comment by lzutao** [comment]
xdg is not our crate. Also the "dirs" crate only follows XDG protocol on Linux/Unix, on Windows
and macOS it use the OS guide convention.

"dirs_next" is not my idea. But we had a vote and other team members chose to go with "dirs_next".

**Comment by Dylan-DPC** [comment]
@pickfire thanks for your suggestions. We had similar ideas last month and we have gone through those to end up on our current conventions. If we ask again, we'll end up going in circles again, discussing the same points over again. I think the ship has sailed. The main reason why we chose that name is so that it's closer to the original and people know that it's the continuation of the maintenance of the original repo.
